# Generated by Django 5.1.3 on 2024-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_seguro_archivo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
